// GENERATES src/content/faqs/home.generated.js — runs in `prebuild`.
//
// ⛔ WHY THIS EXISTS. `src/content/faqs/home.js` selects the homepage's six
// FAQs BY REFERENCE, resolving each answer out of the written service leaf at
// call time. That discipline is correct and is NOT being abandoned here: a
// pasted answer would fork, and a CA correction to a leaf would leave the
// homepage asserting the superseded version indefinitely.
//
// But resolving at RUNTIME means the homepage's JavaScript imports
// `content/services/index.js`, which imports all 31 leaf files — every leaf's
// full prose, FAQ set, document checklists and step lists. Measured on the
// built output: a cold homepage load fetched a 289KB `services-*.js` chunk to
// render six FAQ answers. It is the single largest asset on that page and
// larger than every other item in the Lighthouse "unused JavaScript" audit
// combined. (It is not itself *unused* — it is fully executed — which is
// exactly why the audit never flagged it and why it went unnoticed.)
//
// Resolving at BUILD time keeps the reference discipline and drops the
// payload: the same function runs here, in Node, and its output is written out
// as a small literal module. The generated file is rewritten on every build,
// so it cannot drift from the leaves — the property that made the by-reference
// approach right in the first place.
//
// ⚠️ Adding or changing a homepage FAQ is still not a writing task, and still
// goes in the leaf first. Edit SELECTION in `home.js`; this file follows.
// ⚠️ Never hand-edit `home.generated.js`.

import { writeFileSync, readFileSync } from "node:fs";
import { homeFaqs } from "../src/content/faqs/home.js";

const OUT = new URL("../src/content/faqs/home.generated.js", import.meta.url);

const faqs = homeFaqs();

// `homeFaqs()` drops entries it cannot resolve, and warns while doing it. A
// silent drop that shrinks the row is tolerable at runtime; shipping a build
// with fewer FAQs than the editorial selection asked for is not, so fail here.
const expected = readFileSync(new URL("../src/content/faqs/home.js", import.meta.url), "utf8")
  .split("const SELECTION = [")[1]
  ?.split("];")[0]
  ?.match(/slug:/g)?.length ?? 0;

if (!faqs.length) {
  console.error("[home-faqs] resolved 0 FAQs — refusing to write an empty row");
  process.exit(1);
}
if (expected && faqs.length !== expected) {
  console.error(
    `[home-faqs] SELECTION has ${expected} entries but only ${faqs.length} resolved.\n` +
      "  A question was reworded or a leaf changed. Fix the pointer in\n" +
      "  src/content/faqs/home.js rather than shipping a shorter row."
  );
  process.exit(1);
}

for (const f of faqs) {
  for (const k of ["id", "q", "a", "path", "label"]) {
    if (!f[k]) {
      console.error(`[home-faqs] resolved FAQ "${f.q ?? "?"}" is missing "${k}"`);
      process.exit(1);
    }
  }
}

const body = `// GENERATED by scripts/home-faqs.mjs — DO NOT EDIT.
//
// The homepage's six FAQs, resolved at build time from the written service
// leaves that own them. The editorial selection (which leaf, which question)
// lives in ./home.js; this file is only its resolved output, regenerated on
// every build so it cannot drift from the leaves.
//
// ⚠️ Importing ./home.js from a component pulls in all 31 service leaves
// (~289KB). That is why this file exists — import THIS one from the homepage.

export const homeFaqsResolved = ${JSON.stringify(faqs, null, 2)};
`;

let prev = "";
try {
  prev = readFileSync(OUT, "utf8");
} catch {
  /* first run */
}
if (prev !== body) {
  writeFileSync(OUT, body);
  console.log(`[home-faqs] wrote ${faqs.length} resolved FAQs`);
} else {
  console.log(`[home-faqs] ${faqs.length} resolved FAQs, unchanged`);
}
