// robots.txt, sitemap.xml and llms.txt — the three crawler-facing files that
// are DERIVED from nav.js and lib/seo.js rather than authored.
//
// ⛔ THESE ARE WRITTEN INTO `public/`, NOT `dist/`, AND THIS RUNS AS `prebuild`.
// Clinton, 21-09-2026: "keep all robot txt, site map other seo file do not keep
// in dist folder ... keep in public or src."
//
// The old arrangement wrote them straight into `dist/` from the POSTBUILD
// prerender step. That did work — they were live on Vercel and verifiably
// served — but `dist/` is gitignored, so the files were invisible in the repo
// and existed only after a build. Writing them into `public/` instead means:
//   - they are committed, reviewable, and diff when routes or meta change;
//   - Vite copies `public/` into `dist/` on every build, so they still ship;
//   - they are still DERIVED, so they cannot go stale the way a hand-written
//     sitemap would.
//
// ⚠️ IT HAS TO BE `prebuild`, NOT `postbuild`. Vite copies `public/` during the
// build, so anything written afterwards misses that copy and would not reach
// `dist/` until the NEXT build — i.e. every deploy would ship the previous
// deploy's sitemap. Nothing here needs the built output: `sitemapPaths()` and
// `resolveSeo()` are plain Node modules, which is exactly why this can run
// first. The prerender step keeps the jobs that genuinely need `dist/` (the
// route HTML, the redirect stubs, the og:image assertion).
//
// ⛔ DO NOT HAND-EDIT THE OUTPUT. Each file carries a generated-by banner. Edit
// this script, or the content the script reads.
//
// ⚠️ `sitemap.xml` and `llms.txt` CANNOT become static files in `public/`, only
// generated ones. Both enumerate all 64 routes with their resolved titles and
// descriptions; a hand-maintained copy is a fork of the entire route table and
// would be wrong the first time anyone adds a page.
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { site, sitemapPaths } from "../src/content/nav.js";
import { resolveSeo } from "../src/lib/seo.js";
import { insights } from "../src/content/insights/index.js";
import { noticeDetails } from "../src/content/notices/details.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "public");
const ORIGIN = `https://${site.domain}`;
const BANNER = "Generated by scripts/seo-files.mjs (npm prebuild). Do not edit by hand.";

/**
 * The date a route's CONTENT last changed, or null when we cannot know it.
 *
 * ⛔ PARTIAL ON PURPOSE, AND OMITTING IS THE POINT. Google ignores — and
 * distrusts — a `lastmod` it can tell is mechanical, and the two obvious ways
 * to fill all 64 in are both exactly that:
 *   - Build date on every URL says "all 64 pages changed" on every deploy,
 *     including deploys that only touched CSS. That is a lie told 64 times.
 *   - `git log -1 -- <file>` looks honest and is not reliable HERE: Vercel
 *     builds from a SHALLOW clone, so on the host that actually produces this
 *     file the history is truncated and older pages report the wrong, more
 *     recent date. It would be right locally and wrong in production, which is
 *     the worst combination.
 * So the only dates emitted are ones a human actually authored in the content
 * layer. The spec makes `lastmod` optional per-URL, and the pages where
 * freshness is worth signalling — articles and notices — are precisely the
 * ones that carry a real `published`.
 *
 * ⚠️ If a service leaf ever gains a reviewed-on date, add it here. Do not
 * substitute a proxy.
 */
function lastmodFor(routePath) {
  const article = insights.find((entry) => `/insights/${entry.slug}` === routePath);
  if (article?.published) return article.published;
  const notice = noticeDetails[routePath.replace("/notices/", "")];
  if (routePath.startsWith("/notices/") && notice?.published) return notice.published;
  return null;
}

function writeSitemap(paths) {
  const urls = paths
    .map((p) => {
      const loc = `${ORIGIN}${p === "/" ? "/" : p}`;
      const lastmod = lastmodFor(p);
      return lastmod
        ? `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`
        : `  <url>\n    <loc>${loc}</loc>\n  </url>`;
    })
    .join("\n");
  // ⛔ THE NAMESPACE IS `http://`, NOT `https://`, AND THIS IS NOT A TYPO TO
  // "FIX" BACK. An XML namespace is an opaque identifier, not a URL that gets
  // fetched — `https://...` is a DIFFERENT namespace from the one the sitemap
  // protocol defines, so a strict validator sees an unknown document. Google
  // happens to tolerate it; other tools do not. It shipped wrong until
  // 21-09-2026.
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- ${BANNER} -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
  writeFileSync(path.join(OUT, "sitemap.xml"), xml, "utf-8");
}

/**
 * llms.txt — a plain-language map of the site for AI assistants and the
 * answer engines that increasingly sit in front of search.
 *
 * ⚠️ DERIVED, NEVER AUTHORED. Every line comes from `sitemapPaths()` and
 * `resolveSeo()` — the same two functions the sitemap and every <head> block
 * use — so it cannot list a route that does not exist or describe a page
 * differently from its own meta description. A hand-written version of this
 * file is a fork of the whole site map, and it would be stale within a week.
 *
 * ⚠️ It is an emerging convention, not a standard, and no crawler is obliged
 * to read it. It costs one generated file, so the asymmetry is worth it. If it
 * ever needs to say something the meta descriptions do not, fix the
 * descriptions.
 */
function writeLlmsTxt(paths) {
  // Ordered, so the file reads as a table of contents rather than a dump.
  // Anything not matched by a prefix falls into "Other pages" — a new section
  // of the site therefore still appears, just unsorted, instead of vanishing.
  const groups = [
    ["Services", (p) => p.startsWith("/services")],
    ["Digital Signature Certificates", (p) => p.startsWith("/dsc")],
    ["Insights", (p) => p.startsWith("/insights")],
    ["Notices", (p) => p.startsWith("/notices")],
    ["Company", (p) => ["/about", "/contact", "/partner-with-us"].includes(p)],
  ];
  const seen = new Set();
  const lines = [
    `<!-- ${BANNER} -->`,
    "",
    `# ${site.legalName}`,
    "",
    `> ${resolveSeo("/").description}`,
    "",
    `Registered office: ${site.registeredAddress.full}, ${site.region}, India.`,
    // ⚠️ Stated because the whole point of this file is to be read literally
    // by something summarising the business, and a city in the address is the
    // easiest thing in the world to mistake for the service area.
    "Services are delivered to clients across India; the Salem address is the registered office, not a limit on who we work with.",
    `Contact: ${site.phoneDisplay} · ${site.email}`,
    "",
  ];
  for (const [heading, match] of groups) {
    const members = paths.filter((p) => p !== "/" && match(p));
    if (!members.length) continue;
    lines.push(`## ${heading}`, "");
    for (const p of members) {
      seen.add(p);
      const { title, description } = resolveSeo(p);
      lines.push(`- [${title}](${ORIGIN}${p}): ${description}`);
    }
    lines.push("");
  }
  const rest = paths.filter((p) => p !== "/" && !seen.has(p));
  if (rest.length) {
    lines.push("## Other pages", "");
    for (const p of rest) {
      const { title, description } = resolveSeo(p);
      lines.push(`- [${title}](${ORIGIN}${p}): ${description}`);
    }
    lines.push("");
  }
  writeFileSync(path.join(OUT, "llms.txt"), lines.join("\n"), "utf-8");
}

function writeRobots() {
  const txt = `# ${BANNER}\nUser-agent: *\nAllow: /\n\nSitemap: ${ORIGIN}/sitemap.xml\n`;
  writeFileSync(path.join(OUT, "robots.txt"), txt, "utf-8");
}

const allPaths = sitemapPaths();

// ⛔ A noindex page must not be listed in sitemap.xml. A sitemap is a request
// to index; pairing it with a noindex tag asks for two opposite things, and
// Search Console reports the result as an error ("Submitted URL marked
// noindex"). `resolveSeo` is the ONE place that decides indexability — see the
// `isPlaceholder` note in src/lib/seo.js — so this filter reads that decision
// rather than keeping its own list of placeholder routes to drift from it.
const paths = allPaths.filter((p) => !/noindex/.test(resolveSeo(p).robots));
const excluded = allPaths.length - paths.length;

// llms.txt keeps the FULL set on purpose: it is a map of the site for a reader
// that asked for one, not a crawl request, and "this page exists but is still
// being written" is useful context rather than noise.
writeSitemap(paths);
writeRobots();
writeLlmsTxt(allPaths);
console.log(
  `[seo-files] public/robots.txt, public/sitemap.xml (${paths.length} urls` +
    (excluded ? `, ${excluded} noindex excluded` : "") +
    `), public/llms.txt`
);
